### ISSUE TITLE
Envio de valores do sensor para o Admin

### ISSUE THREAD

**Issue by pwener** [autochopp/embedded_electronics#1]
Galera, para nos enviar os dados do sensor basta mandar uma requisição POST para o seguinte URL:

https://fast-retreat-18030.herokuapp.com/sensors/

Que é nosso ambiente de produção! Na especificação de casos de teste determinamos um intervalo no qual essa requisição precisa ser feita. Outra coisa, precisamos convencionar o nome dos parâmetros, portanto definam aqui qual nome de cada parâmetro enviado, exemplo:

```
weight_value: 500,
choopp_amount: 50,
...
```

Ficará implícito a unidade de medida, portanto coloquem aqui também como parte da nossa convenção para comunicação(Só para manter a rastreabilidade).

Referências:
http://docs.python-requests.org/en/master/user/quickstart/

**Comment by ithallojunior** [comment]
left_volume_on_reservoir: 50,
available_reservoirs: 2,
chosen_cup_volume: 500,
actual_volume_on cup: 490;
temperature: 1,
foam_level: LOW,
cup_on_place: True,
cups_on_shelf: 30

**Comment by pwener** [comment]
Done.
