### ISSUE TITLE
Aquisição de dados dos sensores de forma externa.

### ISSUE THREAD

**Issue by pwener** [autochopp/embedded_electronics#2]
As possíveis soluções que consigo ver:
1. Expor os dados dos sensores via webservice, tal que na Rasp rode um servidor web.
2. Comunicação via socket

### Principais vantagens

1. Webservice
   a. O App de admin poderá acessar diretamente os dados dos sensores.
   b. Não precisamos do intermédio do servidor no heroku, então sem mudanças na nossa api.
   c. É extensível.

2. Socket
   a. É mais seguro, simples e rápido.
   b. Dado será disponibilizado somente quando for requisitado.

### Principais desvantagens
1. Webservice
   a. A Rasp vai ter um processo que consome muito recurso....

2. Socket
   a. Criação de suporte da API à comunicação via socket.

OBS: 
 - Em todas soluções o endereço da Rasp precisa ser fixo.

**Comment by pwener** [comment]
Conforme conversado, vou fazer um webservice bem leve em java:

http://sparkjava.com/tutorials/reducing-java-boilerplate

@ithallojunior e @Oziel-Silva sabem como posso ler esses dados diretamente dos sensores em java?

**Comment by ithallojunior** [comment]
@pwener  diretamente, creio que não há forma direta, como falamos. Ou tem de ser via arquivo ou socket.

**Comment by pwener** [comment]
Done.
